### ISSUE TITLE
Support for -ext and other Exiftool options?

### ISSUE THREAD

**Issue by akillmer** [Sobesednik/node-exiftool#1] opened 2016-07-12 11:35 UTC
Firstly, thank you for this sharing this project. It's been working very well with an Electron app that I've been developing.

Am I missing something or is it possible to pass additional options via `readMetadata(...)`? For example, I can call `readMetadata('/home/Pictures', [ 'r' ])` and Exiftool is able to recursively process all files. 

But if I specify to only process DNG files with `readMetadata('/home/Pictures', [ 'ext dng', 'r' ])` I get this error: _Warning: Invalid tag name 'ext dng' - /home/Pictures/First_Image_Found.jpg_

This would be a helpful new feature so we can take advantage of Exiftool's batch processing performance.

**Comment by z-vr** [comment] 2016-07-24 11:32
@mix-plate hi, thanks for your feedback, I'll have a look into this issue more deeply (and write tests) when I have time. For now, I think the problem is that because `exiftool` is open with `stay_open` flag, it expects all arguments to be on a new line. You can try to pass `'ext\ndng'`, let me know if that helps.

**Comment by z-vr** [comment] 2016-11-27 19:06
@akillmer This should now be fixed in version `2.1.0`, do you mind checking please? Thank you.

**Closed as completed** 2021-06-14 08:41 UTC
